var prefs_,sieve_res_local;RegExp.escape=function(s){return s.replace(/[\/\\^$-.+*?|(){}[\]]/g,"\\$&")};var withBaseURI=function(base,link,addProtocol){if(link[1]==="/"&&link[0]==="/"){if(addProtocol)return base.slice(0,base.indexOf(":")+1)+link;return link}if(/^[\w-]{2,20}:/i.test(link))return link;return base.replace(link[0]==="/"?/(\/\/[^\/]+)\/.*/:/(\/)[^\/]*(?:[?#].*)?$/,"$1")+link};
var updateSieve=function(local_update,callback){var xhr=new XMLHttpRequest;xhr.onload=function(){this.onload=null;try{if(!local_update&&!this.responseText)throw new Error("HTTP "+this.status);var rule,temp_sieve;var new_sieve=JSON.parse(this.responseText);var local_sieve=JSON.parse(cfg.getItem("sieve")||null);if(local_sieve){temp_sieve={};for(rule in local_sieve){if(rule==="dereferers")break;if(new_sieve[rule])continue;temp_sieve[rule]=local_sieve[rule]}for(rule in new_sieve)temp_sieve[rule]=new_sieve[rule];
new_sieve=temp_sieve}updatePrefs({"sieve":new_sieve},true);console.info(app.name+": Sieve updated from "+(local_update?"local":"remote")+" repository.");if(typeof callback==="function")callback()}catch(ex){if(!local_update&&!cfg.getItem("sieve"))updateSieve(true);console.warn(app.name+": Sieve failed to update from "+(local_update?"local":"remote")+" repository! | ",ex.message)}};xhr.overrideMimeType("application/json;charset=utf-8");xhr.open("GET",local_update?withBaseURI(document.baseURI,"sieve.jsn"):
cfg.getItem("sieve_repository"),true);xhr.send(null)};
var updatePrefs=function(sent_prefs,force_update){if(!sent_prefs)sent_prefs={};var def_prefs=new XMLHttpRequest;def_prefs.overrideMimeType("application/json;charset=utf-8");def_prefs.open("GET",withBaseURI(document.baseURI,"defaults.jsn"),false);def_prefs.send(null);def_prefs=JSON.parse(def_prefs.responseText);var need_to_update,mode,pref;var new_prefs={};var new_sieve=[];var skip_sieve=!sent_prefs.sieve&&prefs_;for(mode in def_prefs){if(skip_sieve&&mode==="sieve")continue;need_to_update=false;if(typeof def_prefs[mode]===
"object"){new_prefs[mode]=sent_prefs[mode]||JSON.parse(cfg.getItem(mode)||(Array.isArray(def_prefs[mode])?"[]":"{}"));if(!Array.isArray(def_prefs[mode]))for(pref in def_prefs[mode])if(new_prefs[mode][pref]===void 0||typeof new_prefs[mode][pref]!==typeof def_prefs[mode][pref]){new_prefs[mode][pref]=(!prefs_||prefs_[mode][pref]===void 0?def_prefs:prefs_)[mode][pref];need_to_update=true}}else{pref=sent_prefs[mode]||cfg.getItem(mode)||def_prefs[mode];if(typeof pref!==typeof def_prefs[mode])pref=def_prefs[mode];
if(!prefs_||prefs_[mode]!==pref)need_to_update=true;new_prefs[mode]=pref}if(need_to_update||force_update)cfg.setItem(mode,typeof new_prefs[mode]==="object"?JSON.stringify(new_prefs[mode]):new_prefs[mode])}sent_prefs=null;if(!skip_sieve){if(typeof new_prefs.sieve==="string")new_prefs.sieve=JSON.parse(new_prefs.sieve);sieve_res_local=[];for(mode in new_prefs.sieve){pref=new_prefs.sieve[mode];if(!pref.link&&!pref.img||pref.img&&!pref.to&&!pref.res)continue;try{if(pref.off)throw"off";if(!window.chrome&&
!window.mx&&typeof Components==="undefined"){if(pref.link)pref.link=RegExp(pref.link,pref.ci&&pref.ci&1?"i":"");if(pref.img)pref.img=RegExp(pref.img,pref.ci&&pref.ci&2?"i":"")}if(pref.res)if(/^:\n/.test(pref.res)){sieve_res_local[new_sieve.length]=pref.res.slice(2);pref.res=1}else{if(pref.res.indexOf("\n")>-1){def_prefs=pref.res.split(/\n+/);pref.res=RegExp(def_prefs[0]);if(def_prefs[1])pref.res=[pref.res,RegExp(def_prefs[1])]}else pref.res=RegExp(pref.res);sieve_res_local[new_sieve.length]=pref.res;
pref.res=true}}catch(ex){if(typeof ex==="object")console.error(mode,pref,ex);continue}if(pref.to&&pref.to.indexOf("\n")>0&&pref.to.indexOf(":\n")!==0)pref.to=pref.to.split("\n");delete pref.note;new_sieve.push(pref)}}new_prefs.sieve=skip_sieve?prefs_.sieve:new_sieve;if(new_prefs.grants){pref=new_prefs.grants||[];sent_prefs=[];for(mode=0;mode<pref.length;++mode){if(pref[mode].op===";")continue;if(pref[mode].op.length===2)pref[mode].url=RegExp(pref[mode].url,"i");sent_prefs.push(pref[mode])}if(sent_prefs.length)new_prefs.grants=
sent_prefs;else delete new_prefs.grants}prefs_=new_prefs;if(!cfg.getItem("sieve"))updateSieve(true)};
var onMessage=function(ev,origin,postMessage){var msg,e;if(origin===null)msg=ev;else{e=Port.parse_msg(ev,origin,postMessage);msg=e.msg}if(!msg.cmd)return;switch(msg.cmd){case "hello":var i,l,grants,blockaccess=false,site_prefs={hz:prefs_.hz,sieve:prefs_.sieve,tls:prefs_.tls,keys:prefs_.keys};if(prefs_.grants){grants=prefs_.grants;for(i=0,l=grants.length;i<l;++i)if(grants[i].url==="*"||grants[i].op[1]&&grants[i].url.test(e.origin)||e.origin.indexOf(grants[i].url)>-1)blockaccess=grants[i].op[0]==="!"?
true:false}e.postMessage({"cmd":"hello","prefs":blockaccess?null:site_prefs});break;case "cfg_get":if(!Array.isArray(msg.keys))msg.keys=[msg.keys];var result={};msg.keys.forEach(function(el){result[el]=cfg.getItem(el)});e.postMessage({"cfg":result});break;case "cfg_del":if(!Array.isArray(msg.keys))msg.keys=[msg.keys];msg.keys.forEach(function(el){cfg.removeItem(el)});break;case "getLocaleList":var lxhr=new XMLHttpRequest;lxhr.overrideMimeType("application/json;charset=utf-8");lxhr.open("GET","locales.jsn",
true);lxhr.onload=function(){this.onload=null;e.postMessage(this.responseText)};lxhr.send(null);break;case "broadcast":updatePrefs(msg.prefs,true);Port.broadcast();break;case "update_sieve":updateSieve(false,function(){e.postMessage({"updated_sieve":cfg.getItem("sieve")})});break;case "download":if(msg.url&&typeof saveURI==="function")saveURI({url:msg.url,name:msg.name,showDialog:msg.showDialog});break;case "history":if(typeof to_fromHistory==="function")to_fromHistory(msg.url,msg.manual);break;case "clipboard":if(typeof copyToClipboard===
"function")copyToClipboard(msg.copy);break;case "open":if(!Array.isArray(msg.url))msg.url=[msg.url];Tabs.getSelected(function(tab){for(var i=0;i<msg.url.length;++i)Tabs.create({"incognito":!!tab["incognito"],"url":msg.url[i],"active":!msg.nf})});break;case "resolve_cache":if(!msg.cache)return;_sessionStorage[msg.url]=(prefs_.sieve[msg.rule_id].res_c?~~(Date.now()/1E3)+"|":"")+msg.cache;break;case "resolve":var c_res,rule,data={"cmd":"resolved","id":msg.id,"m":null,"params":msg.params};if(prefs_.tls.sieveCacheRes&&
!data.params.rule.skip_resolve)c_res=_sessionStorage[msg.url];rule=prefs_.sieve[data.params.rule.id];if(c_res!==void 0&&(!rule.res_c||rule.res_c*60>Date.now()/1E3-c_res.slice(0,10))){data.m=JSON.parse(c_res[10]==="|"?c_res.slice(11):c_res)||null;data.cache=true;data.params.url=msg.url;e.postMessage(data);return}if(!/^https?:/.test(msg.url)){console.warn(app.name+": URL pattern doesn't match: "+msg.url);return}var post_params=/([^\s]+)(?: +:(.+)?)?/.exec(msg.url);msg.url=post_params[1];if(data.params.rule.req_res)data.params.rule.req_res=
sieve_res_local[data.params.rule.id];if(data.params.rule.skip_resolve){data.params.url=[""];e.postMessage(data);return}if(!post_params[2])post_params[2]=null;if(rule.res===1){data.m=true;data.params._="";data.params.url=[post_params[1],post_params[2]]}post_params=post_params[2];var xhr=new XMLHttpRequest;xhr.onloadend=function(){this.onloadend=null;var base_url,match;if(/^(image|video|audio)\//i.test(this.getResponseHeader("Content-Type"))){data.m=msg.url;data.noloop=true;console.warn(app.name+": rule "+
data.params.rule.id+" matched against an image file");e.postMessage(data);return}base_url=this.responseXML&&this.responseXML.baseURI;if(!base_url){base_url=this.responseText.slice(0,4096);if(base_url=/<base\s+href\s*=\s*("[^"]+"|'[^']+')/.exec(base_url))base_url=withBaseURI(msg.url,base_url[1].slice(1,-1).replace(/&amp;/g,"&"),true);else base_url=msg.url}if(rule.res===1){data.params._=this.responseText;data.params.base=base_url.replace(/(\/)[^\/]*(?:[?#].*)*$/,"$1");e.postMessage(data);return}var _match=
sieve_res_local[data.params.rule.id];_match=(Array.isArray(_match)?_match:[_match]).map(function(el){var sel=el.source||el;if(sel.indexOf("$")===-1)return el;var group=data.params.length;group=Array.apply(null,Array(group)).map(function(_,i){return i}).join("|");group=RegExp("([^\\\\]?)\\$("+group+")","g");group=!group.test(sel)?el:sel.replace(group,function(m,prefix,id){return id<data.params.length&&prefix!=="\\"?prefix+(data.params[id]?RegExp.escape(data.params[id]):""):m});return typeof el==="string"?
group:RegExp(group)});match=_match[0].exec(this.responseText);if(match){var match_param=data.params.rule.loop_param;if(rule.dc&&(match_param==="link"&&rule.dc!==2||match_param==="img"&&rule.dc>1))match[1]=decodeURIComponent(decodeURIComponent(match[1]));data.m=withBaseURI(base_url,match[1].replace(/&amp;/g,"&"));if(match[2]&&(match=match.slice(1))||_match[1]&&(match=_match[1].exec(this.responseText)))data.m=[data.m,match.filter(function(el,idx){return idx&&el?true:false}).join(" - ")]}else console.info(app.name+
": no match for "+data.params.rule.id);if(prefs_.tls.sieveCacheRes&&data.m)onMessage({"cmd":"resolve_cache","url":msg.url,"cache":JSON.stringify(data.m),"rule_id":data.params.rule.id},null);e.postMessage(data)};xhr.open(post_params?"POST":"GET",msg.url);if(e.isPrivate&&typeof Components==="object")try{xhr.channel.QueryInterface(Ci.nsIPrivateBrowsingChannel).setPrivate(true)}catch(ex){}if(post_params)xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xhr.send(post_params);break}return true};
updatePrefs();Port.listen(onMessage);
(function(){var version;var tmp={};var dayInMsec=24*36E5;var update_version_info=function(params){for(var i in params)version[i]=params[i];cfg.setItem("version",JSON.stringify(version))};try{version=JSON.parse(cfg.getItem("version"));if(!version)throw new Error("version preference is not set!");}catch(ex){version={}}if(version.current!==app.version){tmp.old_ver=version.current;update_version_info({current:app.version,last_check:Date.now()+(Math.random()*14|0)*dayInMsec});if(tmp.old_ver&&(app.version.match(/\./g)||
"").length===2)Tabs.create({"url":"options.html#info/"+(tmp.old_ver||"0"),"active":true});if(tmp.old_ver)updateSieve(true);console.info(app.name+" has been "+(tmp.old_ver?"updated!":"installed!"));return}if(version.last_check&&Date.now()-version.last_check<14*dayInMsec)return;tmp.last_check=version.last_check||0;update_version_info({last_check:Date.now()});return;if(!prefs_.tls.sieveAutoUpdate)return;var xhr=new XMLHttpRequest;xhr.onload=function(){try{var check=JSON.parse(this.responseText);if(tmp.last_check<
check.sieve_ver)updateSieve()}catch(ex){console.warn(app.name+": update check failed!",ex)}};xhr.open("GET","https://googledrive.com/host/0Bx8fnUCX4W2IUTNPT0s2eUFDQms/info.json",true);xhr.send(null)})();
