#! /bin/sh

sxhkd &
feh --bg-fill $HOME/Pictures/winter.jpg
#$HOME/.config/lemonbuddy/launch.sh
compton
xrdb $HOME/.Xresources

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor -d '   ' '   ' '   ' 'files' 'music' 'chat'

bspc monitor -d 'desktop' 'code' 'chrome' 'files' 'music' 'chat'

bspc config border_width         10
bspc config window_gap          40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_by_distance     false
bspc config history_aware_focus   true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config click_to_focus      false
bspc config adaptive raise      true
bspc config center_pseudo_tiled  true


bspc config normal_border_color "#cfcfd1"
bspc config focused_border_color "#E7E8EB"
bspc config presel_feedback_color "#131313"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^3'
bspc rule -a netbeans desktop='^2'
bspc rule -a atom	desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xfce4-panel
$HOME/.config/lemonbuddy/launch.sh
compton --config $HOME/.config/compton.conf
