'use strict';var lg=function(a){this.tC="number"==typeof a?0<a?1:0>a?-1:null:null==a?null:a?-1:1};lg.prototype.uS=function(a,b){var c=0,e=0,f=!1;a=Vb(a,b).split(Zb);for(b=0;b<a.length;b++){var g=a[b];Xb.test(Vb(g,void 0))?(c++,e++):Yb.test(g)?f=!0:Wb.test(Vb(g,void 0))?e++:$b.test(g)&&(f=!0)}return 0==e?f?1:0:.4<c/e?-1:1};lg.prototype.NR=function(a,b){return this.G_(this.uS(a,b))};lg.prototype.G_=function(a){return-1==(0==a?this.tC:a)?"rtl":"ltr"};
lg.prototype.mark=function(){switch(this.tC){case 1:return"\u200e";case -1:return"\u200f";default:return""}};if("undefined"!=typeof angular){var mg=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&mg.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){this.mu=this.Xd=null;a.dirForText=t(function(a){this.Xd||(this.Xd=chrome.i18n.getMessage("@@bidi_dir")||"ltr");this.mu||(this.mu=new lg("rtl"==this.Xd));return this.mu.NR(a||"")},this)}],compile:function(a,b){b=b.key;var c=null,e=document.createElement("amr");
b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&e.setAttribute("id","missing"));if(b){var f=chrome.i18n.getMessage(b+"_ph"),c=[];if(null!=f)for(c=f.split("\ue000"),f=0;f<c.length;++f)c[f]=c[f].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else e.setAttribute("r","nokey");c?e.innerHTML=c:(e.setAttribute("tl","false"),e.innerHTML=a.html());a.replaceWith(e)}}})};var og=/^[\w+/]+[=]{0,2}$/;var pg=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||h,f=e.document,g;(g=(g=(g=(e||h).document.querySelector("script[nonce]"))&&g.getAttribute("nonce"))&&og.test(g)?g:void 0)&&(a.nonce=g);if("help"==a.flow){var k=qa("document.location.href",e);!a.helpCenterContext&&k&&(a.helpCenterContext=k.substring(0,1200));k=!0;if(b&&JSON&&JSON.stringify){var n=JSON.stringify(b);(k=1200>=n.length)&&(a.psdJson=n)}k||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||
"//www.google.com/tools/feedback";if(k=e.GOOGLE_FEEDBACK_START)k.apply(e,b);else{var e=c+"/load.js?",v;for(v in a)b=a[v],null!=b&&!xa(b)&&(e+=encodeURIComponent(v)+"="+encodeURIComponent(b)+"&");a=f.createElement("script");g&&a.setAttribute("nonce",g);a.src=e;f.body.appendChild(a)}};m("userfeedback.api.startFeedback",pg,void 0);var qg=function(a,b,c,e,f,g){this.userEmail=a;this.oH=b;this.HS=c;this.F0=e;this.modelName=f;this.receiverVersion=g};var rg=chrome.i18n.getMessage("4163185390680253103"),sg=chrome.i18n.getMessage("492097680647953484"),tg=chrome.i18n.getMessage("2575016469622936324"),ug=chrome.i18n.getMessage("128276876460319075"),vg=chrome.i18n.getMessage("3326722026796849289"),wg=chrome.i18n.getMessage("1018984561488520517"),xg=chrome.i18n.getMessage("8205999658352447129"),yg=chrome.i18n.getMessage("5723583529370342957"),zg=chrome.i18n.getMessage("1550904064710828958"),Ag=chrome.i18n.getMessage("5014364904504073524"),Bg=chrome.i18n.getMessage("2194670894476780934"),
Cg=chrome.i18n.getMessage("6614468912728530636"),Dg=chrome.i18n.getMessage("5910595154486533449"),Eg=chrome.i18n.getMessage("5363086287710390513"),Fg=chrome.i18n.getMessage("244647017322945605"),Gg=chrome.i18n.getMessage("5375576275991472719"),Hg=chrome.i18n.getMessage("4592127349908255218"),Ig=chrome.i18n.getMessage("843316808366399491"),Jg=chrome.i18n.getMessage("5699813974548050528"),Kg=chrome.i18n.getMessage("8515148417333877999"),Lg=chrome.i18n.getMessage("1636686747687494376"),Mg=chrome.i18n.getMessage("4148300086676792937"),
Ng=chrome.i18n.getMessage("3219866268410307919"),Og=chrome.i18n.getMessage("9211708838274008657"),Pg=chrome.i18n.getMessage("8706273405040403641"),Qg=chrome.i18n.getMessage("4756056595565370923"),Rg=chrome.i18n.getMessage("7876724262035435114"),Sg=chrome.i18n.getMessage("5485620192329479690"),Tg=chrome.i18n.getMessage("6963873398546068901"),Ug=chrome.i18n.getMessage("3567591856726172993"),Vg=chrome.i18n.getMessage("3239956785410157548");var Wg=function(a,b){this.KC=b;this.l=a;this.l.top=a;this.gD=[];this.uA=!1;this.Q$();this.J$();this.K$();this.L$();this.N$();this.KS=Ua();this.l.userEmail="";chrome.identity.getProfileUserInfo(function(a){this.l.userEmail=a.email;this.ko()}.bind(this));this.l.yourAnswerText=Vg;this.l.language=chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.l.requestLogsInProgress=!1};
Wg.prototype.Gt=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};Wg.prototype.Gt.$inject=["$scope","$mdDialog"];Wg.prototype.J$=function(){this.gD=[{value:"Bug",desc:rg},{value:"FeatureRequest",desc:sg},{value:"MirroringQuality",desc:tg},{value:"Discovery",desc:ug},{value:"Other",desc:vg}];this.l.feedbackTypes=this.gD};var Xg=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};d=Wg.prototype;
d.Zz=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new Xg(c,arguments[c]));b.push(new Xg(0,arguments[0]));return b};d.Q$=function(){this.l.videoSmoothnessRatings=this.Zz(Bg,wg,xg,yg,zg,Ag);this.l.videoQualityRatings=this.Zz(Bg,Cg,Dg,Eg,Fg,Gg);this.l.audioQualityRatings=this.Zz(Bg,Hg,Ig,Jg,Kg,Lg)};
d.K$=function(){this.l.includeFineLogs=!0;this.l.feedbackType="Bug";this.l.sendFeedback=t(this.z6,this);this.l.cancel=t(this.nQ,this);this.l.attachLogsClick=t(this.rB,this);this.l.viewLogs=t(this.Vba,this)};d.L$=function(){this.l.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),t(this.EQ,this));this.l.sufficientFeedback=!1};d.N$=function(){this.l.$watch("attachLogs",t(this.rB,this));this.l.attachLogs=!0};
d.nQ=function(){this.l.feedbackDescription&&!confirm(Mg)||window.close()};d.EQ=function(){var a=this.l.feedbackType;this.l.sufficientFeedback="MirroringQuality"==a?this.l.videoSmoothness||this.l.videoQuality||this.l.audioQuality||this.l.comments:"Discovery"==a?this.l.visibleInSetup||this.l.comments:!!this.l.feedbackDescription};
d.z6=function(){if(this.l.sufficientFeedback){var a=this.l.feedbackType,b="";"MirroringQuality"==a?(this.l.videoSmoothness&&(b+="\nVideo Smoothness: "+this.l.videoSmoothness),this.l.videoQuality&&(b+="\nVideo Quality: "+this.l.videoQuality),this.l.audioQuality&&(b+="\nAudio: "+this.l.audioQuality),this.l.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.l.projectedContentUrl),this.l.comments&&(b+="\nComments: "+this.l.comments)):"Discovery"==a?(this.l.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.l.visibleInSetup),this.l.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.l.hasNetworkSoftware),this.l.networkDescription&&(b+="\nNetwork Description: "+this.l.networkDescription),this.l.comments&&(b+="\nComments: "+this.l.comments)):b=this.l.feedbackDescription;this.y6("Type: "+a+"\n\n"+b)}};
d.y6=function(a){this.l.sendDialogText=Ng;this.l.okButton=Ug;this.l.feedbackSent=!1;this.KC.show({locals:{Rja:this.l.feedbackSent,vpa:this.l.sendDialogText,O0:this.l.okButton},scope:this.l,preserveScope:!0,bindToController:!0,template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.Gt});this.XJ(a,u())};d.XJ=function(a,b){var c=u();!this.l.requestLogsInProgress||5E3<c-b?this.aS(a):setTimeout(t(this.XJ,this),1E3,a,b)};
d.aS=function(a){var b=0,c=t(function(a,b){b?a.resolve(!0):(this.l.sendDialogText=Qg,this.ko(),a.reject(Error("Failed to send")))},this),e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable",f=t(function(){b++;var f=I(),k=new qg(this.l.userEmail||"",this.l.logs||"",this.l.externalLogs||"",this.l.mirrorLogUrl||"",this.l.modelName||"",this.l.receiverVersion||""),n=Ca(c,f),v=chrome.runtime.getManifest();pg({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,
locale:v.default_locale,enableAnonymousFeedback:!k.userEmail,report:{description:a},callback:n},{version:v.version,description:v.description,user_email:k.userEmail||"NA",logs:k.oH||"NA",external_logs:k.HS||"NA",device_model:k.modelName||"NA",receiver_version:k.receiverVersion||"NA",dash_report_url:k.F0||"NA"});return f.promise},this);(new Qf(f,1E4,4)).zs(2).start().then(function(){this.l.sendDialogText=Pg;this.l.feedbackSent=!0;this.ko()},function(){this.l.sendDialogText=Og;this.l.feedbackSent=!0;
this.ko()},this)};
d.rB=function(){this.l.logs="";this.l.externalLogs=null;this.l.mirrorLogUrl="";this.l.modelName="";this.l.receiverVersion="";this.l.attachLogs&&(this.l.requestLogsInProgress=!0,chrome.runtime.sendMessage(new kg(this.KS,"retrieve_log_data"),t(function(a){this.l.requestLogsInProgress=!1;this.l.logs=a.logs||"no extension";this.l.mirrorLogUrl=a.castStreamingLogs||"";if((a=a.device)&&a.model&&(this.l.modelName=a.model,this.l.receiverVersion=a.version||"",!this.uA)){var b=Ua();this.uA=!0;this.l.externalLogs=
hg(a.ip,b,t(this.m2,this))}},this)))};
d.Vba=function(){this.l.logsHeader=Rg;this.l.sendLogs=Sg;this.l.fineLogsWarning=Tg;this.l.okButton=Ug;this.KC.show({locals:{Nga:this.l.attachLogs,oH:this.l.logs,hla:this.l.includeFineLogs,$la:this.l.logsHeader,wpa:this.l.sendLogs,Tja:this.l.fineLogsWarning,O0:this.l.okButton},scope:this.l,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.Gt})};
d.m2=function(a,b){this.uA=!1;this.l.externalLogs="error"==a?null:b;this.l.attachLogs||(this.l.externalLogs=null);this.ko()};d.ko=function(){this.l.$$phase||this.l.$apply()};angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",Wg]);m("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.Fk?!0:!1},void 0);m("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0},void 0);m("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof nc)return oc(a);if(a instanceof qc)return rc(a);if(a instanceof kc)return lc(a);if(a instanceof hc)return ic(a);if(a instanceof tc)return uc(a);throw Error();},void 0);
m("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return rc(b);if("resourceUrl"==a||"templateUrl"==a)return oc(b);if("url"==a)return b instanceof nc?oc(b):lc(b);if("css"==a)return ic(b);if("js"==a)return uc(b);throw Error();},void 0);
